services:
  api:
    build: .
    container_name: compose-api
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=appdb
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    container_name: compose-mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
